# Generated by Django 4.1.4 on 2023-03-23 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_publish', models.BooleanField(default=True)),
                ('ordering', models.PositiveSmallIntegerField(default=99)),
            ],
        ),
    ]
