# Generated by Django 4.1.4 on 2023-04-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='시리즈')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='series',
            field=models.ManyToManyField(to='blog.series', verbose_name='시리즈'),
        ),
    ]
