# Generated by Django 4.1.4 on 2023-04-07 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_series_post_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
