# Generated by Django 4.1.4 on 2023-04-08 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
