# Generated by Django 4.1.4 on 2023-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_img_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='img_file',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
