# Generated by Django 4.1.4 on 2023-04-09 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_category_img_file_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
